name: Run Console 

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 10 minutes

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checkout your code repository
      - name: Run "console"
        run: |  # Multi-line script with commands
          sudo timedatectl set-timezone America/New_York  # Set timezone
          chmod 754 console.sh                           # Make console.sh executable
          cp base.md README.md                           # Copy base.md to README.md
          ./console.sh | tee -a README.md                 # Run console.sh and append output
          echo '```' >> README.md                         # Add code block marker
          git config user.name github-actions            # Configure Git user name
          git config user.email github-actions@github.com  # Configure Git user email
          git add README.md                              # Add README.md to commit
          git commit -m "Run console"                      # Commit changes with message
          git push                                         # Push changes to remote


